name: All test

on:
    push:
        branches: ['master']
    pull_request:
        branches: ['master']

permissions:
    contents: write
    pages: write
    id-token: write

jobs:
    test:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node-version: [22.x]
        steps:
            - uses: actions/checkout@v3
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v3
              with:
                  node-version: ${{ matrix.node-version }}
            - name: Init enviroument
              run: |
                  npm i pnpm -g
                  cd lambda-calculus-with-js
                  rm -rf package-lock.json
                  pnpm i
                  pnpm i
            - name: Test
              run: |
                  cd lambda-calculus-with-js
                  pnpm test
            - name: Lint
              run: |
                  cd lambda-calculus-with-js
                  pnpm lint



